version: '3.9'
services:
  nginx:
    container_name: test-nginx
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/
  php:
    container_name: test-php
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./src/public:/var/www/
  mysql:
    container_name: test-mysql
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
